name: Run Test Cases

on:
  pull_request:
    branches:
      - master
env:
  ENVIRONMENT: test
  AWS_ACCESS_KEY_ID: local
  AWS_SECRET_ACCESS_KEY: local
  AWS_REGION: us-east-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo "Running test cases"