name: Run Test Cases

on:
  pull_request:
    branches:
      - master

env:
  ENVIRONMENT: test
  AWS_ACCESS_KEY_ID: ${{ secrets.PLG_PROD_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PLG_PROD_SECRET_KEY }}
  AWS_REGION: us-east-1

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:1.6.21
        ports:
          - 11211:11211

      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
    
      localkms:
        image: nsmithuk/local-kms
        ports:
          - 4599:8080
        volumes:
          - ./init:/init
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          KMS_ACCOUNT_ID: 111122223333
          KMS_REGION: us-east-1
          KMS_SEED_PATH: /init/seed.yaml

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
        
      - name: Build Custom docker file for KMS
        run: |
          echo "Building docker image"
          docker build -t local-kms -f Dockerfile.github .
          echo "Starting docker container for local-kms"
          docker run -d --name localkms -e AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }} -e AWS_REGION=us-east-1 -e KMS_ACCOUNT_ID=111122223333 -e KMS_REGION=us-east-1 -e KMS_SEED_PATH=init/seed.yaml local-kms

      - name: Log into Docker Container
        run: |
          echo "Getting container id"
          container_id=$(docker ps -q -f ancestor=nsmithuk/local-kms)
          echo "Container id: $container_id"
          echo "Checking seed path"
          seed_path=$(docker exec $container_id ls /init)
          echo "Seed path: $seed_path"

      - run: |-
          echo "Start: run test cases"
          sh ./mvnw clean test
          echo "Done: run test cases"
