name: Run Test Cases

on:
  pull_request:
    branches:
      - master
      - salesforce_connect

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:1.6.21
        ports:
          - 11211:11211
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - run: |-
          source ./set_testing_env_vars.sh
          echo "Start: test case run"
          ./mvnw test
          echo "Done: test case run"